version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-backend
    environment:
      - MONGODB_URI=mongodb+srv://kakashi195289:6FEPqu40yd8ph2u2@cluster0.xcmdxwq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - PORT=5000
      - NODE_ENV=production
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:5000/api
    container_name: todo-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: